version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  minio:
    image: minio/minio:latest
    container_name: university_cloud_minio
    env_file:
      - ./.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - minio
      - db
    env_file:
      - ./.env
    volumes:
      # Монтируем папку логов для доступа с хоста
      - ./logs/django:/app/logs

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
      - minio
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.28.0-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./route.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  minio_data:
  db: